# XOR using Perceptron

In [1]:
import numpy as np

In [2]:
X = np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
Y = np.array([0,0,0,1])

In [46]:
rand = np.random.RandomState(0) 

inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 3,1,1

hidden_weights = rand.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))

output_weights = rand.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))


def sigmoid (x):
    return 1/(1 + np.exp(-x))
def activation(X,W):
    hidden_layer_activation = np.dot(X,hidden_weights)
    
    hidden_layer_output = sigmoid(hidden_layer_activation)
    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    
    predicted_output = sigmoid(output_layer_activation)
    return predicted_output
def perceptron(X,Y,lr = 0.1,num_epoch = 100):
    
    
        
    
    return W
    





In [47]:
activation(X,W)

array([[0.58713924],
       [0.602047  ],
       [0.60583215],
       [0.61583677]])

In [48]:
def sigmoid_derivative(x):
    return x * (1 - x)
#Backpropagation
predicted_output = activation(X,W)
error = Y - predicted_output
d_predicted_output = error * sigmoid_derivative(predicted_output)
print(d_predicted_output)

# yeh ek 4*4 matrix aa rha.. joh aage fir multiply ni ho pa rha

error_hidden_layer = d_predicted_output.dot(output_weights.T)
d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)
#Updating Weights and Biases
output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr

hidden_weights += inputs.T.dot(d_hidden_layer) * lr



[[-0.14232652 -0.14232652 -0.14232652  0.10008024]
 [-0.14424228 -0.14424228 -0.14424228  0.09534413]
 [-0.14467245 -0.14467245 -0.14467245  0.09412711]
 [-0.1456958  -0.1456958  -0.1456958   0.09088604]]


ValueError: shapes (4,4) and (1,1) not aligned: 4 (dim 1) != 1 (dim 0)